const express = require('express');
const cors = require('cors');
const morgan = require('morgan');
const carData = require('./car_data.json');

const app = express();
const PORT = process.env.PORT || 3000;

// تعطيل الـ Etag لجميع المسارات في السيرفر
app.disable('etag');

// إعدادات الوسيطات الأساسية
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true })); // لدعم قراءة بيانات نموذج تسجيل الدخول المرسلة من التطبيق
app.use(morgan('dev'));

// إجبار جميع الردود على عدم التخزين المؤقت لمنع ظهور حالة 304
app.use((req, res, next) => {
    res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate');
    res.setHeader('Pragma', 'no-cache');
    res.setHeader('Expires', '0');
    next();
});

// مسار التحقق الأساسي
app.get('/', (req, res) => {
    res.status(200).json({
        success: true,
        message: 'السيرفر يعمل وجاهز لتوجيه طلبات التطبيق بنجاح!'
    });
});

// 1. مسار تسجيل الدخول (POST /api/login)
app.post('/api/login', (req, res) => {
    const { user_name, password } = req.body;
    
    // يمكنك هنا طباعة البيانات المرسلة للاطلاع عليها
    console.log('محاولة تسجيل دخول لـ:', user_name);

    res.status(200).json({
        data: {
            "access_token": "eyJ0eXAiOiJqd3QifQ.eyJzdWIiOiIxIiwiaXNzIjoiaHR0cDpcL1wvOiIsImV4cCI6MzA1MDI4ODUzNSwiaWF0IjoxNzg4ODQ4NTM1LCJuYmYiOjE3ODg4NDg1MzUsInVpZCI6NDgwMzkzMiwicyI6InBobmFYciIsImp0aSI6ImQ3YTNmYWM1MzJhNjNmODlkMmVkNDEwZjlhYmM0YTlmIn0.8aYhNP83mCgk7vx1JgqnyWvgCnRiC43Q5z7mN_oPSQ8",
            "token_type": "Bearer",
            "goloToken": "A473277A8372D6D5C4B9C174678094F5pfvx",
            "cc": "505371899",
            "user_id": 4803932,
            "name": user_name ? user_name.split('@')[0] : "yfkhgfhh",
            "contact_way": "",
            "refresh_ttl": 604800,
            "api_cloud": "https://hasan-mohammad.onrender.com",
            "api_download": "https://hasan-mohammad.onrender.com",
            "avatar": ""
        },
        code: 0,
        message: "success",
        time: Math.floor(Date.now() / 1000)
    });
});

// 2. مسار إعدادات التطبيق (GET /api/app_config)
app.get('/api/app_config', (req, res) => {
    const myServer = 'https://hasan-mohammad.onrender.com';

    res.status(200).json({
        code: 0,
        message: "success",
        data: {
            "VIP_URL": `${myServer}/vip`,
            "SOFTWARE_PAY_URL": `${myServer}/pay`,
            "SOFTWARE_PLANS_URL": `${myServer}/plans`,
            "MUCAR_RESET": `${myServer}/mucar_reset`,
            "Thinkdiag_Reset": `${myServer}/thinkdiag_reset`,
            "Ediag_software": `${myServer}/ediag`,
            "DIAG_GPT_URL": `${myServer}/ai/gpt`,
            "DIAG_FCRM_URL": `${myServer}/fcrm`,
            "DIAG_HELP_URL": `${myServer}/help`,
            "DIAG_SERVICE_URL": `${myServer}/service`,
            "DIAG_FAQ_URL": `${myServer}/faq`,
            "DIAG_DIAG_HELP_URL": `${myServer}/diag_help`,
            "DIAG_CONTACT_US_URL": `${myServer}/contact`,
            "DIAG_REDEEM_URL": `${myServer}/redeem`,
            "DIAG_POINTS_URL": `${myServer}/points`,
            "DIAG_INVITE_URL": `${myServer}/invite`,
            "DIAG_ACTIVATE_SN_URL": `${myServer}/activate`,
            "DIAG_MEMBER_RECORD_URL": `${myServer}/record`,
            "SOFTWARE_DETAIL_H5": `${myServer}/software_detail`,
            "RESET_DETAIL_H5": `${myServer}/reset_detail`,
            "VIN_RESET_DETAIL_H5": `${myServer}/vin_reset_detail`,
            "ORDER_LIST_DETAIL_H5": `${myServer}/orders`,
            "VIN_DETAIL_H5": `${myServer}/vin_detail`,
            "AI_VEHICLE": `${myServer}/ai/vehicle`,
            "EXCELLENT_PRODUCT_DETAIL_H5": `${myServer}/product/excellent`,
            "COMBINATION_PRODUCT_DETAIL_H5": `${myServer}/product/combination`,
            "DIAG_INTEGRAL_CENTER_H5": `${myServer}/integral/center`,
            "COMBINATION_LIST_H5": `${myServer}/combination/list`,
            "HOT_PRODUCT_DETAIL_H5": `${myServer}/product/hot`,
            "COMMUNITY_MALL_LIST_H5": `${myServer}/mall/list`,
            "DIAGNOSTIC_LIST_H5": `${myServer}/diagnostic/list`,
            "DIAG_INTEGRAL_MALL_H5": `${myServer}/integral/mall`,
            "MALL_DETAILS_H5": `${myServer}/mall/details`,
            "LUCKY_POINTS_H5": `${myServer}/luckypoints`,
            "NEW_LUCKY_POINTS_H5": `${myServer}/new_luckypoints`,
            "PRIVATE_TEST_LAB_H5": `${myServer}/lab`,
            "REPORT_LIST_H5": `${myServer}/reports`,
            "PULL_IN_FISSION_H5": `${myServer}/fission`,
            "CAR_CALLBACK_HOME_H5": `${myServer}/car/callback`,
            "CAR_SECURITY_RATING_H5": `${myServer}/car/security`,
            "FAULT_LIGHT_LIST_H5": `${myServer}/fault/lights`,
            "DIAG_INTEGRAL_RULE_H5": `${myServer}/integral/rule`,
            "COMMUNITY_PROTOCOL_H5": `${myServer}/protocol`,
            "AI_PREDICTION": `${myServer}/ai/prediction`,
            "GATEWAY_CENTER_URL": `${myServer}/gateway/center`,
            "GATEWAY_VAG_URL": `${myServer}/gateway/vag`,
            "GATEWAY_BENZ_URL": `${myServer}/gateway/benz`,
            "GATEWAY_RENAULT_URL": `${myServer}/gateway/renault`,
            "GATEWAY_FCA_URL": `${myServer}/gateway/fca`,
            "MY_COUPONS_LIST_URL": `${myServer}/coupons`,
            "AI_ANALYSE": `${myServer}/ai/analyse`,
            "AI_REPAIR": `${myServer}/ai/repair`,
            "AI_PLAN": `${myServer}/ai/plan`,
            "AI_FUNCTION_EQUITY": `${myServer}/ai/equity`
        },
        time: Math.floor(Date.now() / 1000),
        ip: req.headers['x-forwarded-for'] || req.socket.remoteAddress || "127.0.0.1"
    });
});
app.get('/api/v2/debice/Hassan eList', (req, res) => {
    res.json({
        data: {
            list: [
                {
                    id: 401,
                    softName: "Demo",
                    softPackageID: "DEMO",
                    erpCode: "X0387",
                    softType: 1,
                    serverCurrentTime: 1788788908313,
                    price: 0,
                    priceUnit: 1,
                    isHotModel: 0,
                    is_free: 1,
                    free_date: 0,
                    renew_diagnosis_sign: 0,
                    scan_plus_system: 0,
                    fileSize: 63283837,
                    versionNo: "V10.66",
                    platType: 2,
                    androidSoftId: 72792,
                    iosSoftId: 62550,
                    is_renew: null,
                    is_send: null,"downloadLink": "https://downloadapp.mythinkcar.com/app_soft/DEMO/2/V10.66/Arabic/DEMO_THINKDIAG1_V10.66_AR.zip",
        "zyVersion": "V15.56",
        "isNewPath": 0,
        "versionDetailId": 2654,
        "softUpdateTime": 1722304322667,
        "softApplicableAreaId": 10,
        "lanType": "Arabic",
        "lanId": "12",
        "availableEndTime": null
      },
      {
        "id": 397,
        "softName": "Iveco",
        "softPackageID": "IVECO",
        "erpCode": "X0384",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 9163195,
        "versionNo": "V10.42",
        "platType": 2,
        "androidSoftId": 75733,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/IVECO/2/V10.42/English/IVECO_THINKDIAG_V10.42_EN.zip",
        "zyVersion": "V22.05",
        "isNewPath": 1,
        "versionDetailId": 2296,
        "softUpdateTime": 1654507656921,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 396,
        "softName": "JMC",
        "softPackageID": "ISUZU",
        "erpCode": "X0383",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 9427466,
        "versionNo": "V10.46",
        "platType": 2,
        "androidSoftId": 75203,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/ISUZU/2/V10.46/English/ISUZU_THINKDIAG_V10.46_EN.zip",
        "zyVersion": "V14.01",
        "isNewPath": 1,
        "versionDetailId": 2601,
        "softUpdateTime": 1654507632519,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 392,
        "softName": "Changhe",
        "softPackageID": "CHANGHE",
        "erpCode": "X0379",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 10826703,
        "versionNo": "V10.14",
        "platType": 2,
        "androidSoftId": 75209,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/CHANGHE/2/V10.14/English/CHANGHE_THINKDIAG_V10.14_EN.zip",
        "zyVersion": "V20.63",
        "isNewPath": 1,
        "versionDetailId": 2373,
        "softUpdateTime": 1646130682308,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 380,
        "softName": "Soueast",
        "softPackageID": "DONGNAN",
        "erpCode": "X0368",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 9471203,
        "versionNo": "V10.12",
        "platType": 2,
        "androidSoftId": 78132,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/DONGNAN/2/V10.12/English/DONGNAN_THINKDIAG_V10.12_EN.zip",
        "zyVersion": "V20.84",
        "isNewPath": 1,
        "versionDetailId": 1966,
        "softUpdateTime": 1641376873820,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 360,
        "softName": "Adaptive Front Lighting",
        "softPackageID": "RESETAFS",
        "erpCode": "X0350",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 126278295,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71794,
        "iosSoftId": 70698,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETAFS/2/V10.02/English/RESETAFS_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1290,
        "softUpdateTime": 1641985069447,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 359,
        "softName": "EGR Adaption",
        "softPackageID": "RESETEGR",
        "erpCode": "X0349",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 22137664,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71462,
        "iosSoftId": 70700,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETEGR/2/V10.02/English/RESETEGR_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1273,
        "softUpdateTime": 1641903630932,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 355,
        "softName": "TPMS(Reset)",
        "softPackageID": "RESETTPMS",
        "erpCode": "X0345",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 152355492,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71883,
        "iosSoftId": 62635,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETTPMS/2/V10.02/English/RESETTPMS_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1295,
        "softUpdateTime": 1641985232799,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 354,
        "softName": "Air Level Calibration",
        "softPackageID": "RESETSUS",
        "erpCode": "X0343",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 134313834,
        "versionNo": "V10.00",
        "platType": 2,
        "androidSoftId": 71903,
        "iosSoftId": 70702,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETSUS/2/V10.00/English/RESETSUS_THINKDIAG_V10.00_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 197,
        "softUpdateTime": 1641985222835,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 353,
        "softName": "Sunroof Initialization ",
        "softPackageID": "RESETSUN",
        "erpCode": "X0342",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 22480795,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71478,
        "iosSoftId": 70701,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETSUN/2/V10.02/English/RESETSUN_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1276,
        "softUpdateTime": 1744801762272,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 350,
        "softName": "Steering Angle Reset",
        "softPackageID": "RESETSAS",
        "erpCode": "X0339",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 365,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 264793960,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71856,
        "iosSoftId": 62588,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETSAS/2/V10.02/English/RESETSAS_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1298,
        "softUpdateTime": 1641985199897,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 348,
        "softName": "Oil Maintenance Reset",
        "softPackageID": "RESETOIL",
        "erpCode": "X0337",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 365,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 201868348,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71477,
        "iosSoftId": 62616,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETOIL/2/V10.02/English/RESETOIL_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 0,
        "versionDetailId": 1291,
        "softUpdateTime": 1661779330974,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 343,
        "softName": "Injector Coding ",
        "softPackageID": "RESETINJEC",
        "erpCode": "X0332",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 161554859,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71872,
        "iosSoftId": 62650,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETINJEC/2/V10.02/English/RESETINJEC_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1292,
        "softUpdateTime": 1641985174741,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 342,
        "softName": "Immobilizer Reset",
        "softPackageID": "RESETIMMO",
        "erpCode": "X0331",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 193715565,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71449,
        "iosSoftId": 62636,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETIMMO/2/V10.02/English/RESETIMMO_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1294,
        "softUpdateTime": 1641985161014,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 337,
        "softName": "Electric Throttle Relearn",
        "softPackageID": "RESETETS",
        "erpCode": "X0326",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 168148982,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71791,
        "iosSoftId": 62639,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETETS/2/V10.02/English/RESETETS_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1293,
        "softUpdateTime": 1641985149692,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 335,
        "softName": "DPF Regen",
        "softPackageID": "RESETDPF",
        "erpCode": "X0324",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 159613165,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71880,
        "iosSoftId": 62562,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETDPF/2/V10.02/English/RESETDPF_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1297,
        "softUpdateTime": 1641985129061,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 333,
        "softName": "Brake Reset",
        "softPackageID": "RESETBRAKE",
        "erpCode": "X0322",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 263350262,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71887,
        "iosSoftId": 62488,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETBRAKE/2/V10.02/English/RESETBRAKE_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1274,
        "softUpdateTime": 1641903467810,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 332,
        "softName": "Gearbox Relearn",
        "softPackageID": "RESETBOX",
        "erpCode": "X0321",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 36520152,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71444,
        "iosSoftId": 70699,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETBOX/2/V10.02/English/RESETBOX_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1275,
        "softUpdateTime": 1642215988402,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 331,
        "softName": "Battery Matching",
        "softPackageID": "RESETBMS",
        "erpCode": "X0320",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 136078603,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71461,
        "iosSoftId": 62663,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETBMS/2/V10.02/English/RESETBMS_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1296,
        "softUpdateTime": 1642215952922,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 330,
        "softName": "ABS Bleeding",
        "softPackageID": "RESETBLEED",
        "erpCode": "X0319",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 164982600,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71491,
        "iosSoftId": 62520,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETBLEED/2/V10.02/English/RESETBLEED_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1272,
        "softUpdateTime": 1641985081662,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 319,
        "softName": "Mahindra (India)",
        "softPackageID": "INDIANMAHINDRA",
        "erpCode": "X0309",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 7006800,
        "versionNo": "V10.40",
        "platType": 2,
        "androidSoftId": 91430,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/INDIANMAHINDRA/2/V10.40/English/INDIANMAHINDRA_THINKDIAG_V10.40_EN.zip",
        "zyVersion": "V15.30",
        "isNewPath": 1,
        "versionDetailId": 2144,
        "softUpdateTime": 1640775895570,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 311,
        "softName": "Peugeot",
        "softPackageID": "PEUGEOT",
        "erpCode": "X0301",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 93354005,
        "versionNo": "V10.60",
        "platType": 2,
        "androidSoftId": 71733,
        "iosSoftId": 62649,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/PEUGEOT/2/V10.60/English/PEUGEOT_THINKDIAG_V10.60_EN.zip",
        "zyVersion": "V44.15",
        "isNewPath": 1,
        "versionDetailId": 2609,
        "softUpdateTime": 1654507894878,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 262,
        "softName": "BMW/Rolls Royce/Mini",
        "softPackageID": "BMW",
        "erpCode": "X0252",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 1233210911,
        "versionNo": "V10.72",
        "platType": 2,
        "androidSoftId": 71673,
        "iosSoftId": 62640,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/BMW/2/V10.72/English/BMW_THINKDIAG_V10.72_EN.zip",
        "zyVersion": "V51.66",
        "isNewPath": 0,
        "versionDetailId": 2372,
        "softUpdateTime": 1661827583541,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 261,
        "softName": "Renault/Dacia/Samsung Renault",
        "softPackageID": "RENAULT",
        "erpCode": "X0251",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 73655058,
        "versionNo": "V10.66",
        "platType": 2,
        "androidSoftId": 72723,
        "iosSoftId": 62641,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RENAULT/2/V10.66/English/RENAULT_THINKDIAG_V10.66_EN.zip",
        "zyVersion": "V43.95",
        "isNewPath": 1,
        "versionDetailId": 2498,
        "softUpdateTime": 1654507922512,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 260,
        "softName": "MERCEDES-BENZ",
        "softPackageID": "BENZ",
        "erpCode": "X0250",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 1034070527,
        "versionNo": "V11.28",
        "platType": 2,
        "androidSoftId": 71712,
        "iosSoftId": 62492,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/BENZ/2/V11.28/English/BENZ_THINKDIAG_V11.28_EN.zip",
        "zyVersion": "V50.50",
        "isNewPath": 0,
        "versionDetailId": 2493,
        "softUpdateTime": 1660642647222,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 259,
        "softName": "Ford",
        "softPackageID": "USAFORD",
        "erpCode": "X0249",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 61422700,
        "versionNo": "V11.44",
        "platType": 2,
        "androidSoftId": 71703,
        "iosSoftId": 62565,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/USAFORD/2/V11.44/English/USAFORD_THINKDIAG_V11.44_EN.zip",
        "zyVersion": "V50.65",
        "isNewPath": 1,
        "versionDetailId": 2617,
        "softUpdateTime": 1654507528842,
        "softApplicableAreaId": 1,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 257,
        "softName": "Roewe (SAIC)",
        "softPackageID": "SAICROEWE",
        "erpCode": "X0247",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 23182826,
        "versionNo": "V10.36",
        "platType": 2,
        "androidSoftId": 75703,
        "iosSoftId": 62574,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SAICROEWE/2/V10.36/English/SAICROEWE_THINKDIAG_V10.36_EN.zip",
        "zyVersion": "V13.65",
        "isNewPath": 1,
        "versionDetailId": 2503,
        "softUpdateTime": 1654507947119,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 256,
        "softName": "MG (SAIC)",
        "softPackageID": "SAICMG",
        "erpCode": "X0246",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 23475299,
        "versionNo": "V10.38",
        "platType": 2,
        "androidSoftId": 75699,
        "iosSoftId": 62661,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SAICMG/2/V10.38/English/SAICMG_THINKDIAG_V10.38_EN.zip",
        "zyVersion": "V13.52",
        "isNewPath": 1,
        "versionDetailId": 2384,
        "softUpdateTime": 1654507878833,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 254,
        "softName": "Nissan/Infiniti/GTR (Nissan)",
        "softPackageID": "NISSAN",
        "erpCode": "X0244",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 92793578,
        "versionNo": "V10.56",
        "platType": 2,
        "androidSoftId": 71710,
        "iosSoftId": 62622,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/NISSAN/2/V10.56/English/NISSAN_THINKDIAG_V10.56_EN.zip",
        "zyVersion": "V46.10",
        "isNewPath": 1,
        "versionDetailId": 2308,
        "softUpdateTime": 1654166144362,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 253,
        "softName": "Land Rover/Jaguar",
        "softPackageID": "LANDROVER",
        "erpCode": "X0243",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 116836274,
        "versionNo": "V10.74",
        "platType": 2,
        "androidSoftId": 71643,
        "iosSoftId": 62471,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/LANDROVER/2/V10.74/English/LANDROVER_THINKDIAG_V10.74_EN.zip",
        "zyVersion": "V35.10",
        "isNewPath": 1,
        "versionDetailId": 2613,
        "softUpdateTime": 1666857708456,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 251,
        "softName": "Chrysler/Dodge/Jeep",
        "softPackageID": "CHRYSLER",
        "erpCode": "X0241",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 40923645,
        "versionNo": "V11.16",
        "platType": 2,
        "androidSoftId": 71705,
        "iosSoftId": 62528,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/CHRYSLER/2/V11.16/English/CHRYSLER_THINKDIAG1_V11.16_EN.zip",
        "zyVersion": "V35.40",
        "isNewPath": 1,
        "versionDetailId": 2371,
        "softUpdateTime": 1654507435491,
        "softApplicableAreaId": 1,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 242,
        "softName": "Suzuki",
        "softPackageID": "SUZUKI",
        "erpCode": "X0232",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 26659200,
        "versionNo": "V10.50",
        "platType": 2,
        "androidSoftId": 71640,
        "iosSoftId": 62521,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SUZUKI/2/V10.50/English/SUZUKI_THINKDIAG_V10.50_EN.zip",
        "zyVersion": "V39.05",
        "isNewPath": 1,
        "versionDetailId": 2437,
        "softUpdateTime": 1693895247256,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 238,
        "softName": "SGM/Buick (China)",
        "softPackageID": "SGM",
        "erpCode": "X0228",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 42126643,
        "versionNo": "V10.72",
        "platType": 2,
        "androidSoftId": 75730,
        "iosSoftId": 62486,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SGM/2/V10.72/English/SGM_THINKDIAG_V10.72_EN.zip",
        "zyVersion": "V53.60",
        "isNewPath": 1,
        "versionDetailId": 2306,
        "softUpdateTime": 1641985308355,
        "softApplicableAreaId": 1,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 230,
        "softName": "Isuzu/Isuzu (Thailand)",
        "softPackageID": "JPISUZU",
        "erpCode": "X0220",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 18126997,
        "versionNo": "V10.48",
        "platType": 2,
        "androidSoftId": 71648,
        "iosSoftId": 62491,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/JPISUZU/2/V10.48/English/JPISUZU_THINKDIAG_V10.48_EN.zip",
        "zyVersion": "V18.10",
        "isNewPath": 1,
        "versionDetailId": 2608,
        "softUpdateTime": 1645411993612,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 228,
        "softName": "GM/Chevrolet/Cadillac/Buick",
        "softPackageID": "GM",
        "erpCode": "X0218",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 80961979,
        "versionNo": "V11.22",
        "platType": 2,
        "androidSoftId": 71666,
        "iosSoftId": 62476,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/GM/2/V11.22/English/GM_THINKDIAG_V11.22_EN.zip",
        "zyVersion": "V49.95",
        "isNewPath": 1,
        "versionDetailId": 2310,
        "softUpdateTime": 1654509748652,
        "softApplicableAreaId": 1,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 226,
        "softName": "EOBD/OBDII",
        "softPackageID": "EOBD2",
        "erpCode": "X0216",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 6907673,
        "versionNo": "V10.28",
        "platType": 2,
        "androidSoftId": 71472,
        "iosSoftId": 62525,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/EOBD2/2/V10.28/English/EOBD2_THINKDIAG_V10.28_EN.zip",
        "zyVersion": "V23.03",
        "isNewPath": 0,
        "versionDetailId": 1317,
        "softUpdateTime": 1662697588310,
        "softApplicableAreaId": 10,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 225,
        "softName": "Sprinter",
        "softPackageID": "SPRINTER",
        "erpCode": "X0215",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 61638616,
        "versionNo": "V10.46",
        "platType": 2,
        "androidSoftId": 71716,
        "iosSoftId": 62620,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SPRINTER/2/V10.46/English/SPRINTER_THINKDIAG_V10.46_EN.zip",
        "zyVersion": "V21.92",
        "isNewPath": 1,
        "versionDetailId": 2344,
        "softUpdateTime": 1654507962727,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 224,
        "softName": "Smart",
        "softPackageID": "SMART",
        "erpCode": "X0214",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 24931517,
        "versionNo": "V10.22",
        "platType": 2,
        "androidSoftId": 71638,
        "iosSoftId": 62524,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SMART/2/V10.22/English/SMART_THINKDIAG_V10.22_EN.zip",
        "zyVersion": "V18.45",
        "isNewPath": 1,
        "versionDetailId": 2385,
        "softUpdateTime": 1648693627926,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 216,
        "softName": "Brilliance",
        "softPackageID": "HUACHEN",
        "erpCode": "X0205",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 15722214,
        "versionNo": "V10.24",
        "platType": 2,
        "androidSoftId": 75206,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/HUACHEN/2/V10.24/English/HUACHEN_THINKDIAG_V10.24_EN.zip",
        "zyVersion": "V30.94",
        "isNewPath": 0,
        "versionDetailId": 2226,
        "softUpdateTime": 1652358167909,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 214,
        "softName": "BYD",
        "softPackageID": "FLYER",
        "erpCode": "X0203",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 38334762,
        "versionNo": "V10.24",
        "platType": 2,
        "androidSoftId": 75653,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/FLYER/2/V10.24/English/FLYER_THINKDIAG_V10.24_EN.zip",
        "zyVersion": "V19.70",
        "isNewPath": 1,
        "versionDetailId": 1509,
        "softUpdateTime": 1653370500681,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 210,
        "softName": "VOLKSWAGEN",
        "softPackageID": "VW",
        "erpCode": "X0199",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 85161132,
        "versionNo": "V10.40",
        "platType": 2,
        "androidSoftId": 71719,
        "iosSoftId": 62543,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/VW/2/V10.40/English/VW_THINKDIAG_V10.40_EN.zip",
        "zyVersion": "V29.10",
        "isNewPath": 0,
        "versionDetailId": 2305,
        "softUpdateTime": 1660642825245,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 209,
        "softName": "Citroen",
        "softPackageID": "CITROEN",
        "erpCode": "X0198",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 74128661,
        "versionNo": "V10.30",
        "platType": 2,
        "androidSoftId": 71735,
        "iosSoftId": 62566,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/CITROEN/2/V10.30/English/CITROEN_THINKDIAG_V10.30_EN.zip",
        "zyVersion": "V42.01",
        "isNewPath": 1,
        "versionDetailId": 1924,
        "softUpdateTime": 1654507465122,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 207,
        "softName": "Nissan (Zhengzhou)",
        "softPackageID": "ZZNISSAN",
        "erpCode": "X0196",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 11990778,
        "versionNo": "V10.28",
        "platType": 2,
        "androidSoftId": 81490,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/ZZNISSAN/2/V10.28/English/ZZNISSAN_THINKDIAG_V10.28_EN.zip",
        "zyVersion": "V12.11",
        "isNewPath": 1,
        "versionDetailId": 2076,
        "softUpdateTime": 1683207139632,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 206,
        "softName": "Zotye",
        "softPackageID": "ZHONGTAI",
        "erpCode": "X0195",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 8852348,
        "versionNo": "V10.06",
        "platType": 2,
        "androidSoftId": 75680,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/ZHONGTAI/2/V10.06/English/ZHONGTAI_THINKDIAG_V10.06_EN.zip",
        "zyVersion": "V18.20",
        "isNewPath": 1,
        "versionDetailId": 2242,
        "softUpdateTime": 1640778295637,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 199,
        "softName": "Subaru",
        "softPackageID": "SUBARU",
        "erpCode": "X0189",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 25184889,
        "versionNo": "V10.68",
        "platType": 2,
        "androidSoftId": 71708,
        "iosSoftId": 62547,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SUBARU/2/V10.68/English/SUBARU_THINKDIAG_V10.68_EN.zip",
        "zyVersion": "V26.41",
        "isNewPath": 1,
        "versionDetailId": 2238,
        "softUpdateTime": 1640777796851,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 198,
        "softName": "Ssangyong",
        "softPackageID": "SSANGYONG",
        "erpCode": "X0188",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 39844033,
        "versionNo": "V10.12",
        "platType": 2,
        "androidSoftId": 75674,
        "iosSoftId": 62596,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SSANGYONG/2/V10.12/English/SSANGYONG_THINKDIAG_V10.12_EN.zip",
        "zyVersion": "V19.70",
        "isNewPath": 1,
        "versionDetailId": 2615,
        "softUpdateTime": 1646136740449,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 197,
        "softName": "Skoda",
        "softPackageID": "SKODA",
        "erpCode": "X0187",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 67225047,
        "versionNo": "V10.18",
        "platType": 2,
        "androidSoftId": 71714,
        "iosSoftId": 62542,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SKODA/2/V10.18/English/SKODA_THINKDIAG_V10.18_EN.zip",
        "zyVersion": "V28.57",
        "isNewPath": 0,
        "versionDetailId": 2386,
        "softUpdateTime": 1660642839003,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 196,
        "softName": "Seat",
        "softPackageID": "SEAT",
        "erpCode": "X0186",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 68119878,
        "versionNo": "V10.20",
        "platType": 2,
        "androidSoftId": 71465,
        "iosSoftId": 62477,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SEAT/2/V10.20/English/SEAT_THINKDIAG_V10.20_EN.zip",
        "zyVersion": "V28.52",
        "isNewPath": 1,
        "versionDetailId": 2237,
        "softUpdateTime": 1640777640119,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 188,
        "softName": "Chery",
        "softPackageID": "QIRUI_TY",
        "erpCode": "X0176",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 17739137,
        "versionNo": "V10.22",
        "platType": 2,
        "androidSoftId": 75202,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/QIRUI_TY/2/V10.22/English/QIRUI_TY_THINKDIAG_V10.22_EN.zip",
        "zyVersion": "V57.83",
        "isNewPath": 1,
        "versionDetailId": 2383,
        "softUpdateTime": 1640770530424,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 179,
        "softName": "Mitsubishi",
        "softPackageID": "MITSUBISHI",
        "erpCode": "X0167",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 80662346,
        "versionNo": "V10.48",
        "platType": 2,
        "androidSoftId": 71470,
        "iosSoftId": 62647,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/MITSUBISHI/2/V10.48/English/MITSUBISHI_THINKDIAG_V10.48_EN.zip",
        "zyVersion": "V35.65",
        "isNewPath": 1,
        "versionDetailId": 2435,
        "softUpdateTime": 1654507998457,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 177,
        "softName": "Proton (Malaysia)",
        "softPackageID": "MALAYSIA PROTON",
        "erpCode": "X0165",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 11949618,
        "versionNo": "V10.12",
        "platType": 2,
        "androidSoftId": 95778,
        "iosSoftId": 62617,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/MALAYSIA PROTON/2/V10.12/English/MALAYSIA PROTON_THINKDIAG_V10.12_EN.zip",
        "zyVersion": "V15.11",
        "isNewPath": 1,
        "versionDetailId": 1786,
        "softUpdateTime": 1645514552548,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 176,
        "softName": "Perodua (Malaysia)",
        "softPackageID": "MALAYSIA PERODUA",
        "erpCode": "X0164",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 7073620,
        "versionNo": "V10.16",
        "platType": 2,
        "androidSoftId": 91433,
        "iosSoftId": 62516,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/MALAYSIA PERODUA/2/V10.16/English/MALAYSIA PERODUA_THINKDIAG_V10.16_EN.zip",
        "zyVersion": "V14.60",
        "isNewPath": 1,
        "versionDetailId": 1764,
        "softUpdateTime": 1645514562396,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      
                        {
                    "id": 174,
                    "softName": "Luxgen",
                    "softPackageID": "LUXGEN",
                    "erpCode": "X0162",
                    "softType": 1,
                    "serverCurrentTime": 1788788908313,
                    "price": 0,
                    "priceUnit": 1,
                    "isHotModel": 0,
                    "is_free": 1,
                    "free_date": 0,
                    "renew_diagnosis_sign": 0,
                    "scan_plus_system": 0,
                    "fileSize": 4381413,
                    "versionNo": "V10.00",
                    "platType": 2,
                    "androidSoftId": 75683,
                    "iosSoftId": 62666,
                    "is_renew": null,
                    "is_send": null,
                    "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/LUXGEN/2/V10.00/English/LUXGEN_V10.00_EN.zip",
                    "zyVersion": "V15.56",
                    "isNewPath": 0,
                    "versionDetailId": 1764,
                    "softUpdateTime": 1645514562396,
                    "softApplicableAreaId": 0,
                    "lanType": "English",
                    "lanId": 1001,
                    "availableEndTime": null
                }
            ]
        }
    });
});
app.get('/api/newAdvertise', (req, res) => {
    res.status(200).json({
        "code": 0,
        "message": "success",
        "time": Math.floor(Date.now() / 1000),
        "data": {
            "advertising": [
                {
                    "id": 56,
                    "title": "免费试用推广",
                    "route_type": 1,
                    "img": [
                        "https://thinkcar123.s3.us-west-1.amazonaws.com/admin-file/ad_images-16759058284533.png"
                    ],
                    "url": "",
                    "sn_segment": [],
                    "timing": 43200,
                    "duration": 3,
                    "interval": 0,
                    "type": "1"
                },
                {
                    "title": "默认广告",
                    "route_type": 0,
                    "img": [
                        "https://thinkcar123.s3.us-west-1.amazonaws.com/images/512dd668d7a0b9544bc70609327c6877.jpeg"
                    ],
                    "timing": 43200,
                    "duration": 3,
                    "sn_segment": [],
                    "options_id": 7,
                    "url": "https://www.baidu.com",
                    "interval": 0,
                    "type": "2"
                }
            ],
            "product": [],
            "customized": {
                "cc": "501526711",
                "device_sn": "979860000004",
                "token": "5D6B734968F331481D2AFB731C14494Brm0z"
            },
            "thinkeasy": "https://www.mythinkcar.com/",
            "thinkdiag": "https://www.mythinkcar.com/",
            "vip_url": "https://user.thinkcar.com/api/member/vip_url",
            "gpt_url": "https://h5.mythinkcar.com/vueh5/other/gpt2",
            "lamp_url": ""
        }
    });
});
app.get('/api/observer-users', (req, res) => {
    res.setHeader('Server', 'nginx');
    res.setHeader('Cache-Control', 'private, must-revalidate');
    res.setHeader('Pragma', 'no-cache');
    res.setHeader('Expires', '-1');
    res.setHeader('X-RateLimit-Limit', '1200');
    res.setHeader('X-RateLimit-Remaining', '1199');
    res.setHeader('Access-Control-Allow-Origin', '*');
    
    res.status(200).json({
        "code": 0,
        "message": "",
        "data": {
            "users": [
                3407523, 3056301, 3434039, 3006520, 3033630, 3461769, 
                3723936, 3730279, 3701717, 3725471, 3750891, 3746548, 
                3711151, 3561401, 3737098, 3749316, 3755283, 3746745, 
                3756180, 3678265, 3741697, 3685642, 3750052, 3756527, 
                3715488, 2013270, 3751370, 3752157, 3441538, 3726445, 
                3097795, 3741001, 3714284, 3754819, 3759454, 3737963, 
                3765494, 3728812, 3679798, 3729212, 3679798, 3196028, 
                3692467, 3759728, 3366201, 3728127, 3801218, 3636869, 
                2042181, 3155118, 3768728, 5136622
            ]
        },
        "time": 1788941894
    });
});
app.get('/api/get_fca_order_url', (req, res) => {
    res.setHeader('Server', 'nginx');
    res.setHeader('Strict-Transport-Security', 'max-age=31536000');
    res.setHeader('Access-Control-Allow-Origin', '*');
    
    res.status(200).json({
        "data": {
            "url": "https://thinkcarpay.com/m/FCA_describe?logintype=androidapp&lang=ar&app_id=9053&theme=&sn=&token=Bearer+eyJ0eXAiOiJqd3QifQ.eyJzdWIiOiIxIiwiaXNzIjoiaHR0cDpcL1wvOiIsImV4cCI6MzA1MDI4ODUzNSwiaWF0IjoxNzg4ODQ4NTM1LCJuYmYiOjE3ODg4NDg1MzUsInVpZCI6NDgwMzkzMiwicyI6InBobmFYciIsImp0aSI6ImQ3YTNmYWM1MzJhNjNmODlkMmVkNDEwZjlhYmM0YTlmIn0.8aYhNP83mCgk7vx1JgqnyWvgCnRiC43Q5z7mN_oPSQ8&channel_type=1&channel=1&app_type=1&good_id=174&isNorthAmerica=false&identification=FCA_describe",
            "ip": "150.228.11.224",
            "continent": "亚洲"
        },
        "code": 0,
        "message": "success",
        "time": 1788941895
    });
});
app.get('/api/userLog/config', (req, res) => {
    res.setHeader('Server', 'nginx');
    res.setHeader('Cache-Control', 'private, must-revalidate');
    res.setHeader('Pragma', 'no-cache');
    res.setHeader('Expires', '-1');
    res.setHeader('X-RateLimit-Limit', '1200');
    res.setHeader('X-RateLimit-Remaining', '1198');
    res.setHeader('Access-Control-Allow-Origin', '*');
    
    res.status(200).json({
        "code": 0,
        "message": "",
        "data": {
            "is_open": 0
        },
        "time": 1788941894
    });
});
app.post('/api/buried-point', (req, res) => {
    res.setHeader('Server', 'nginx');
    res.setHeader('Cache-Control', 'private, must-revalidate');
    res.setHeader('Pragma', 'no-cache');
    res.setHeader('Expires', '-1');
    res.setHeader('X-RateLimit-Limit', '1200');
    res.setHeader('X-RateLimit-Remaining', '1197');
    res.setHeader('Access-Control-Allow-Origin', '*');

    res.status(429).json({
        "code": 429,
        "message": "Exceeded the maximum number of requests.",
        "data": [],
        "time": 1788941895
    });
});
app.get('/api/golo_retrieve', (req, res) => {
    res.setHeader('Server', 'nginx');
    res.setHeader('Strict-Transport-Security', 'max-age=31536000');
    res.setHeader('Access-Control-Allow-Origin', '*');

    res.status(200).json({
        "data": {
            "goloToken": "FEF85015854D6B70B2108649966762F44sur",
            "cc": "505371899",
            "user_id": 4803932,
            "email": "jdhdjzdjjdv@gmail.com"
        },
        "code": 0,
        "message": "success",
        "time": 1788947548
    });
});
app.get('/api/get/new_version', (req, res) => {
    res.setHeader('Server', 'nginx');
    res.setHeader('Strict-Transport-Security', 'max-age=31536000');
    res.setHeader('Access-Control-Allow-Origin', '*');

    res.status(200).json({
        "data": {
            "id": 4787,
            "version": "3.2.8",
            "version_code": 123,
            "app_name": "ThinkDiag+",
            "package_name": "com.thinkcar.app",
            "app_id": 9053,
            "description": "Fix known bugs and optimize product interactive experience.",
            "is_master": 1,
            "is_forced": 0,
            "version_update_time": 1770087035
        },
        "code": 0,
        "message": "success",
        "time": 1788947548
    });
});
app.get('/api/user', (req, res) => {
    res.setHeader('Server', 'nginx');
    res.setHeader('Strict-Transport-Security', 'max-age=31536000');
    res.setHeader('Access-Control-Allow-Origin', '*');

    res.status(200).json({
        "data": {
            "user_id": 4803932,
            "invite_code": "IKCCT2",
            "name": "yfkhgfhh",
            "email": "jdhdjzdjjdv@gmail.com",
            "phone": "",
            "bio": "",
            "sex": 0,
            "location": "",
            "avatar": "",
            "bg": "",
            "job": "",
            "created_at": "2025-10-04 05:05:44",
            "set_password": true,
            "usable_integral": 7,
            "birthday": 0,
            "country": "",
            "contact_way": "",
            "share_email": "",
            "vip_time": 1818165644,
            "is_perpetual": 0,
            "device_number": 0
        },
        "code": 0,
        "message": "success",
        "time": 1788947548
    });
});
app.get('/api/devicn/lisht', (req, res) => {
    res.setHeader('Server', 'nginx');
    res.setHeader('Strict-Transport-Security', 'max-age=31536000');
    res.setHeader('Access-Control-Allow-Origin', '*');

    res.status(200).json({
        "data": {
            "list": [
                {
                    "id": 2290614,
                    "device_type": 3,
                    "device_sn": "​979862374489",
                    "real_device_sn": "​979862374489",
                    "create_time": 1786629644,
                    "is_new_blue": 0,
                    "is_black": 0,
                    "sn_type": "0",
                    "device_name": "THINKDIAG",
                    "new_product": "0",
                    "channelName": "电商,APP,美国",
                    "packageName": "THINKDIAG",
                    "downloadLink": "https://download.mythinkcar.com/productName/1690357133701/ThinkDiag.png"
                }
            ]
        },
        "code": 0,
        "message": "success",
        "time": 1788947548
    });
});
app.get('/api/v4/userg/ga_phfsh_data', (req, res) => {
    res.setHeader('Server', 'nginx');
    res.setHeader('Strict-Transport-Security', 'max-age=31536000');
    res.setHeader('Access-Control-Allow-Origin', '*');

    res.status(200).json({
        "data": {
            "global": {
                "ints": [],
                "strings": {
                    "user_id": "4803932",
                    "key_user_name": "yfkhgfhh",
                    "key_user_email": "jdhdjzdjjdv@gmail.com"
                },
                "floats": []
            },
            "initialize": [
                {
                    "event_name": "key_app_time",
                    "event_params": {
                        "ints": {
                            "key_user_points": 7,
                            "key_user_VIP_expiration_date": 0,
                            "key_user_expiration_date": 0,
                            "key_registration_duration": 341,
                            "key_device_1_activation_duration": 27,
                            "key_device_2_activation_duration": 0,
                            "key_device_3_activation_duration": 0,
                            "key_vip_orders": 0,
                            "key_software_orders": 0
                        },
                        "strings": {
                            "key_user_devices_1": "​979862374489",
                            "key_user_devices_2": "N/A",
                            "key_user_devices_3": "N/A",
                            "key_user_device_erp_code": "N/A",
                            "key_devices_1_erp_code": "30000374",
                            "key_devices_2_erp_code": "N/A",
                            "key_devices_3_erp_code": "N/A"
                        },
                        "floats": {
                            "key_vip_amount": 0,
                            "key_software_amount": 0
                        }
                    }
                },
                {
                    "event_name": "key_user_devices_info",
                    "event_params": {
                        "ints": {
                            "key_device_1_is_pirate": 0,
                            "key_device_2_is_pirate": 0,
                            "key_device_3_is_pirate": 0
                        },
                        "strings": [],
                        "floats": []
                    }
                }
            ],
            "custom": [
                {
                    "event_names": [
                        "key_home_reports",
                        "KEY_HOME_ALL_SYSTEM_DIAGNOSTIC"
                    ],
                    "event_params": {
                        "ints": {
                            "test_1": 1
                        },
                        "strings": {
                            "string_test": "A1"
                        },
                        "floats": []
                    }
                }
            ]
        },
        "code": 0,
        "message": "success",
        "time": 1788947549
    });
});
app.get('/api/notice/ufhead', (req, res) => {
    res.setHeader('Server', 'nginx');
    res.setHeader('Strict-Transport-Security', 'max-age=31536000');
    res.setHeader('Access-Control-Allow-Origin', '*');

    res.status(200).json({
        "data": {
            "user_system": 0,
            "notice": {
                "_id": {
                    "$oid": "6a33d124a8c3e077603234c7"
                },
                "id": 46874100,
                "content": "Dear yfkhgfhh:\r\n\r\nThis is a kindly reminder that your device (979862374455) have 92 software (ASTONMARTIN, etc.) that are remaining validity period of 30 days. \r\n\r\nIn order not to affect your use, you can easily continue subscribing in the app.",
                "type": 4,
                "cover": "",
                "msg_title": "Software Expiration Reminder",
                "link": "",
                "link_remark": "",
                "attached": {
                    "push_notice_info": "4803932",
                    "body": "Dear yfkhgfhh:\r\n\r\nThis is a kindly reminder that your device (776656456) have 92 software (ASTONMARTIN, etc.) that are remaining validity period of 30 days. \r\n\r\nIn order not to affect your use, you can easily continue subscribing in the app.",
                    "title": "Software Expiration Reminder",
                    "type": "order",
                    "cover": "",
                    "msg_title": "",
                    "link": "",
                    "link_remark": "",
                    "push_type": "notice",
                    "channel": "3",
                    "sub_type": "soft_expire",
                    "user_id": "4803932",
                    "extras": []
                },
                "read": false,
                "read_at": "",
                "notifiable_id": "4803932",
                "created_at": "2026-06-18 19:06:12"
            }
        },
        "code": 0,
        "message": "success",
        "time": 1788947673
    });
});
app.get('/api/v2/dgvice/getSoftwareList', (req, res) => {
    res.setHeader('Server', 'nginx');
    res.setHeader('Strict-Transport-Security', 'max-age=31536000');
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.status(200).json(carData);
});
app.get('/api/device/list', (req, res) => {
    res.status(200).json({
        "data": {
            "list": [
                {
                    "id": 2290614,
                    "device_type": 3,
                    "device_sn": "979862374455",
                    "real_device_sn": "979862374455",
                    "create_time": 1786629644,
                    "is_new_blue": 0,
                    "is_black": 0,
                    "sn_type": "0",
                    "device_name": "THINKDIAG",
                    "new_product": "0",
                    "channelName": "电商,APP,美国",
                    "packageName": "THINKDIAG",
                    "downloadLink": "https://download.mythinkcar.com/productName/1690357133701/ThinkDiag.png"
                }
            ]
        },
        "code": 0,
        "message": "success",
        "time": Math.floor(Date.now() / 1000)
    });
});
app.get('/api/v4/user/ga_push_data', (req, res) => {
    res.status(200).json({
        "data": {
            "global": {
                "ints": [],
                "strings": {
                    "user_id": "4803932",
                    "key_user_name": "yfkhgfhh",
                    "key_user_email": "jdhdjzdjjdv@gmail.com"
                },
                "floats": []
            },
            "initialize": [
                {
                    "event_name": "key_app_time",
                    "event_params": {
                        "ints": {
                            "key_user_points": 7,
                            "key_user_VIP_expiration_date": 0,
                            "key_user_expiration_date": 0,
                            "key_registration_duration": 341,
                            "key_device_1_activation_duration": 28,
                            "key_device_2_activation_duration": 0,
                            "key_device_3_activation_duration": 0,
                            "key_vip_orders": 0,
                            "key_software_orders": 0
                        },
                        "strings": {
                            "key_user_devices_1": "979862374455",
                            "key_user_devices_2": "N/A",
                            "key_user_devices_3": "N/A",
                            "key_user_device_erp_code": "N/A",
                            "key_devices_1_erp_code": "30000374",
                            "key_devices_2_erp_code": "N/A",
                            "key_devices_3_erp_code": "N/A"
                        },
                        "floats": {
                            "key_vip_amount": 0,
                            "key_software_amount": 0
                        }
                    }
                },
                {
                    "event_name": "key_user_devices_info",
                    "event_params": {
                        "ints": {
                            "key_device_1_is_pirate": 0,
                            "key_device_2_is_pirate": 0,
                            "key_device_3_is_pirate": 0
                        },
                        "strings": [],
                        "floats": []
                    }
                }
            ],
            "custom": [
                {
                    "event_names": [
                        "key_home_reports",
                        "KEY_HOME_ALL_SYSTEM_DIAGNOSTIC"
                    ],
                    "event_params": {
                        "ints": {
                            "test_1": 1
                        },
                        "strings": {
                            "string_test": "A1"
                        },
                        "floats": []
                    }
                }
            ]
        },
        "code": 0,
        "message": "success",
        "time": Math.floor(Date.now() / 1000)
    });
});

  app.use((req, res) => {
    res.status(404).json({
        success: false,
        message: "المسار غير موجود على سيرفرك"
  });
});

app.listen(PORT, () => {
console.log(`🚀 Server running on port ${PORT}`);
});
