const express = require('express');
const app = express();

const port = process.env.PORT || 3000;

app.use(express.json());

// وسيط لمراقبة الطلبات الواردة وطباعتها في الـ Logs
app.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);
  next();
});
app.post('/api/login', (req, res) => {
  const { username } = req.body;

  res.json({
    "code": 0,
    "message": "success",
    "data": {
      "access_token": "eyJ0eXAiOiJqd3QifQ.eyJzdWIiOiIxIiwiaXNzIjoiaHR0cDpcL1wvOiIsImV4cCI6MzA1MDIyODAxOCwiaWF0IjoxNzg4Nzg4MDE4LCJuYmYiOjE3ODg3ODgwMTgsInVpZCI6NDgwMzkzMiwicyI6IkljTjJXMSIsImp0aSI6ImQ4Njg0YTFmYzZjZWQ0MGQ3Y2UxYWJlMmI1MjcwYzJlIn0.KZwpE7mJuJkjmgYz268vNoTJO5yhQVi_Iq1OYlTSD08",
      "token_type": "Bearer",
      "goloToken": "B2EAB7D45D13B349482F54047E13A906o50w",
      "cc": "505371899",
      "user_id": 4803932,
      "name": username || "yfkhgfhh",
      "contact_way": "",
      "refresh_ttl": 604800,
      "api_cloud": "https://hasan-mohammad.onrender.com",
      "api_download": "https://hasan-mohammad.onrender.com",
      "avatar": ""
    },
        "time": 1788788018

  });
});

app.get('/api/v2/device/getSoftwareList', (req, res) => {
    // يمكنك قراءة القيم المرسلة من الرابط إذا أردت استخدامها
    const deviceSn = req.query.device_sn;
    const lanType = req.query.lan_type;
    const appType = req.query.app_type;

    // ضع الرد هنا بالشكل الذي يتوقعه التطبيق
    res.json({
        code: 0,
        message: "success",
        data: {
            list: [
                {
                    softPackageID: "DEMO",
                    softName: "Demo",
                    versionNo: "V10.66",
                    downloadLink: "https://downloadapp.mythinkcar.com/app_soft/DEMO/2/V10.66/Arabic/DEMO_THINKDIAG1_V10.66_AR.zip",
        "zyVersion": "V15.56",
        "isNewPath": 0,
        "versionDetailId": 2654,
        "softUpdateTime": 1722304322667,
        "softApplicableAreaId": 10,
        "lanType": "Arabic",
        "lanId": "12",
        "availableEndTime": null
      },
      {
        "id": 397,
        "softName": "Iveco",
        "softPackageID": "IVECO",
        "erpCode": "X0384",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 9163195,
        "versionNo": "V10.42",
        "platType": 2,
        "androidSoftId": 75733,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/IVECO/2/V10.42/English/IVECO_THINKDIAG_V10.42_EN.zip",
        "zyVersion": "V22.05",
        "isNewPath": 1,
        "versionDetailId": 2296,
        "softUpdateTime": 1654507656921,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 396,
        "softName": "JMC",
        "softPackageID": "ISUZU",
        "erpCode": "X0383",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 9427466,
        "versionNo": "V10.46",
        "platType": 2,
        "androidSoftId": 75203,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/ISUZU/2/V10.46/English/ISUZU_THINKDIAG_V10.46_EN.zip",
        "zyVersion": "V14.01",
        "isNewPath": 1,
        "versionDetailId": 2601,
        "softUpdateTime": 1654507632519,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 392,
        "softName": "Changhe",
        "softPackageID": "CHANGHE",
        "erpCode": "X0379",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 10826703,
        "versionNo": "V10.14",
        "platType": 2,
        "androidSoftId": 75209,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/CHANGHE/2/V10.14/English/CHANGHE_THINKDIAG_V10.14_EN.zip",
        "zyVersion": "V20.63",
        "isNewPath": 1,
        "versionDetailId": 2373,
        "softUpdateTime": 1646130682308,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 380,
        "softName": "Soueast",
        "softPackageID": "DONGNAN",
        "erpCode": "X0368",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 9471203,
        "versionNo": "V10.12",
        "platType": 2,
        "androidSoftId": 78132,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/DONGNAN/2/V10.12/English/DONGNAN_THINKDIAG_V10.12_EN.zip",
        "zyVersion": "V20.84",
        "isNewPath": 1,
        "versionDetailId": 1966,
        "softUpdateTime": 1641376873820,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 360,
        "softName": "Adaptive Front Lighting",
        "softPackageID": "RESETAFS",
        "erpCode": "X0350",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 126278295,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71794,
        "iosSoftId": 70698,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETAFS/2/V10.02/English/RESETAFS_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1290,
        "softUpdateTime": 1641985069447,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 359,
        "softName": "EGR Adaption",
        "softPackageID": "RESETEGR",
        "erpCode": "X0349",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 22137664,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71462,
        "iosSoftId": 70700,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETEGR/2/V10.02/English/RESETEGR_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1273,
        "softUpdateTime": 1641903630932,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 355,
        "softName": "TPMS(Reset)",
        "softPackageID": "RESETTPMS",
        "erpCode": "X0345",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 152355492,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71883,
        "iosSoftId": 62635,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETTPMS/2/V10.02/English/RESETTPMS_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1295,
        "softUpdateTime": 1641985232799,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 354,
        "softName": "Air Level Calibration",
        "softPackageID": "RESETSUS",
        "erpCode": "X0343",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 134313834,
        "versionNo": "V10.00",
        "platType": 2,
        "androidSoftId": 71903,
        "iosSoftId": 70702,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETSUS/2/V10.00/English/RESETSUS_THINKDIAG_V10.00_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 197,
        "softUpdateTime": 1641985222835,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 353,
        "softName": "Sunroof Initialization ",
        "softPackageID": "RESETSUN",
        "erpCode": "X0342",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 22480795,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71478,
        "iosSoftId": 70701,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETSUN/2/V10.02/English/RESETSUN_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1276,
        "softUpdateTime": 1744801762272,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 350,
        "softName": "Steering Angle Reset",
        "softPackageID": "RESETSAS",
        "erpCode": "X0339",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 365,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 264793960,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71856,
        "iosSoftId": 62588,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETSAS/2/V10.02/English/RESETSAS_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1298,
        "softUpdateTime": 1641985199897,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 348,
        "softName": "Oil Maintenance Reset",
        "softPackageID": "RESETOIL",
        "erpCode": "X0337",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 365,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 201868348,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71477,
        "iosSoftId": 62616,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETOIL/2/V10.02/English/RESETOIL_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 0,
        "versionDetailId": 1291,
        "softUpdateTime": 1661779330974,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 343,
        "softName": "Injector Coding ",
        "softPackageID": "RESETINJEC",
        "erpCode": "X0332",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 161554859,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71872,
        "iosSoftId": 62650,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETINJEC/2/V10.02/English/RESETINJEC_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1292,
        "softUpdateTime": 1641985174741,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 342,
        "softName": "Immobilizer Reset",
        "softPackageID": "RESETIMMO",
        "erpCode": "X0331",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 193715565,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71449,
        "iosSoftId": 62636,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETIMMO/2/V10.02/English/RESETIMMO_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1294,
        "softUpdateTime": 1641985161014,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 337,
        "softName": "Electric Throttle Relearn",
        "softPackageID": "RESETETS",
        "erpCode": "X0326",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 168148982,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71791,
        "iosSoftId": 62639,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETETS/2/V10.02/English/RESETETS_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1293,
        "softUpdateTime": 1641985149692,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 335,
        "softName": "DPF Regen",
        "softPackageID": "RESETDPF",
        "erpCode": "X0324",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 159613165,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71880,
        "iosSoftId": 62562,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETDPF/2/V10.02/English/RESETDPF_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1297,
        "softUpdateTime": 1641985129061,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 333,
        "softName": "Brake Reset",
        "softPackageID": "RESETBRAKE",
        "erpCode": "X0322",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 263350262,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71887,
        "iosSoftId": 62488,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETBRAKE/2/V10.02/English/RESETBRAKE_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1274,
        "softUpdateTime": 1641903467810,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 332,
        "softName": "Gearbox Relearn",
        "softPackageID": "RESETBOX",
        "erpCode": "X0321",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 36520152,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71444,
        "iosSoftId": 70699,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETBOX/2/V10.02/English/RESETBOX_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1275,
        "softUpdateTime": 1642215988402,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 331,
        "softName": "Battery Matching",
        "softPackageID": "RESETBMS",
        "erpCode": "X0320",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 136078603,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71461,
        "iosSoftId": 62663,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETBMS/2/V10.02/English/RESETBMS_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1296,
        "softUpdateTime": 1642215952922,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 330,
        "softName": "ABS Bleeding",
        "softPackageID": "RESETBLEED",
        "erpCode": "X0319",
        "softType": 2,
        "serverCurrentTime": 1788788908313,
        "price": 19.95,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 0,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 164982600,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 71491,
        "iosSoftId": 62520,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RESETBLEED/2/V10.02/English/RESETBLEED_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.80",
        "isNewPath": 1,
        "versionDetailId": 1272,
        "softUpdateTime": 1641985081662,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 319,
        "softName": "Mahindra (India)",
        "softPackageID": "INDIANMAHINDRA",
        "erpCode": "X0309",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 7006800,
        "versionNo": "V10.40",
        "platType": 2,
        "androidSoftId": 91430,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/INDIANMAHINDRA/2/V10.40/English/INDIANMAHINDRA_THINKDIAG_V10.40_EN.zip",
        "zyVersion": "V15.30",
        "isNewPath": 1,
        "versionDetailId": 2144,
        "softUpdateTime": 1640775895570,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 311,
        "softName": "Peugeot",
        "softPackageID": "PEUGEOT",
        "erpCode": "X0301",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 93354005,
        "versionNo": "V10.60",
        "platType": 2,
        "androidSoftId": 71733,
        "iosSoftId": 62649,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/PEUGEOT/2/V10.60/English/PEUGEOT_THINKDIAG_V10.60_EN.zip",
        "zyVersion": "V44.15",
        "isNewPath": 1,
        "versionDetailId": 2609,
        "softUpdateTime": 1654507894878,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 262,
        "softName": "BMW/Rolls Royce/Mini",
        "softPackageID": "BMW",
        "erpCode": "X0252",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 1233210911,
        "versionNo": "V10.72",
        "platType": 2,
        "androidSoftId": 71673,
        "iosSoftId": 62640,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/BMW/2/V10.72/English/BMW_THINKDIAG_V10.72_EN.zip",
        "zyVersion": "V51.66",
        "isNewPath": 0,
        "versionDetailId": 2372,
        "softUpdateTime": 1661827583541,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 261,
        "softName": "Renault/Dacia/Samsung Renault",
        "softPackageID": "RENAULT",
        "erpCode": "X0251",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 73655058,
        "versionNo": "V10.66",
        "platType": 2,
        "androidSoftId": 72723,
        "iosSoftId": 62641,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/RENAULT/2/V10.66/English/RENAULT_THINKDIAG_V10.66_EN.zip",
        "zyVersion": "V43.95",
        "isNewPath": 1,
        "versionDetailId": 2498,
        "softUpdateTime": 1654507922512,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 260,
        "softName": "MERCEDES-BENZ",
        "softPackageID": "BENZ",
        "erpCode": "X0250",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 1034070527,
        "versionNo": "V11.28",
        "platType": 2,
        "androidSoftId": 71712,
        "iosSoftId": 62492,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/BENZ/2/V11.28/English/BENZ_THINKDIAG_V11.28_EN.zip",
        "zyVersion": "V50.50",
        "isNewPath": 0,
        "versionDetailId": 2493,
        "softUpdateTime": 1660642647222,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 259,
        "softName": "Ford",
        "softPackageID": "USAFORD",
        "erpCode": "X0249",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 61422700,
        "versionNo": "V11.44",
        "platType": 2,
        "androidSoftId": 71703,
        "iosSoftId": 62565,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/USAFORD/2/V11.44/English/USAFORD_THINKDIAG_V11.44_EN.zip",
        "zyVersion": "V50.65",
        "isNewPath": 1,
        "versionDetailId": 2617,
        "softUpdateTime": 1654507528842,
        "softApplicableAreaId": 1,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 257,
        "softName": "Roewe (SAIC)",
        "softPackageID": "SAICROEWE",
        "erpCode": "X0247",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 23182826,
        "versionNo": "V10.36",
        "platType": 2,
        "androidSoftId": 75703,
        "iosSoftId": 62574,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SAICROEWE/2/V10.36/English/SAICROEWE_THINKDIAG_V10.36_EN.zip",
        "zyVersion": "V13.65",
        "isNewPath": 1,
        "versionDetailId": 2503,
        "softUpdateTime": 1654507947119,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 256,
        "softName": "MG (SAIC)",
        "softPackageID": "SAICMG",
        "erpCode": "X0246",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 23475299,
        "versionNo": "V10.38",
        "platType": 2,
        "androidSoftId": 75699,
        "iosSoftId": 62661,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SAICMG/2/V10.38/English/SAICMG_THINKDIAG_V10.38_EN.zip",
        "zyVersion": "V13.52",
        "isNewPath": 1,
        "versionDetailId": 2384,
        "softUpdateTime": 1654507878833,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 254,
        "softName": "Nissan/Infiniti/GTR (Nissan)",
        "softPackageID": "NISSAN",
        "erpCode": "X0244",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 92793578,
        "versionNo": "V10.56",
        "platType": 2,
        "androidSoftId": 71710,
        "iosSoftId": 62622,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/NISSAN/2/V10.56/English/NISSAN_THINKDIAG_V10.56_EN.zip",
        "zyVersion": "V46.10",
        "isNewPath": 1,
        "versionDetailId": 2308,
        "softUpdateTime": 1654166144362,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 253,
        "softName": "Land Rover/Jaguar",
        "softPackageID": "LANDROVER",
        "erpCode": "X0243",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 116836274,
        "versionNo": "V10.74",
        "platType": 2,
        "androidSoftId": 71643,
        "iosSoftId": 62471,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/LANDROVER/2/V10.74/English/LANDROVER_THINKDIAG_V10.74_EN.zip",
        "zyVersion": "V35.10",
        "isNewPath": 1,
        "versionDetailId": 2613,
        "softUpdateTime": 1666857708456,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 251,
        "softName": "Chrysler/Dodge/Jeep",
        "softPackageID": "CHRYSLER",
        "erpCode": "X0241",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 40923645,
        "versionNo": "V11.16",
        "platType": 2,
        "androidSoftId": 71705,
        "iosSoftId": 62528,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/CHRYSLER/2/V11.16/English/CHRYSLER_THINKDIAG1_V11.16_EN.zip",
        "zyVersion": "V35.40",
        "isNewPath": 1,
        "versionDetailId": 2371,
        "softUpdateTime": 1654507435491,
        "softApplicableAreaId": 1,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 242,
        "softName": "Suzuki",
        "softPackageID": "SUZUKI",
        "erpCode": "X0232",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 26659200,
        "versionNo": "V10.50",
        "platType": 2,
        "androidSoftId": 71640,
        "iosSoftId": 62521,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SUZUKI/2/V10.50/English/SUZUKI_THINKDIAG_V10.50_EN.zip",
        "zyVersion": "V39.05",
        "isNewPath": 1,
        "versionDetailId": 2437,
        "softUpdateTime": 1693895247256,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 238,
        "softName": "SGM/Buick (China)",
        "softPackageID": "SGM",
        "erpCode": "X0228",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 42126643,
        "versionNo": "V10.72",
        "platType": 2,
        "androidSoftId": 75730,
        "iosSoftId": 62486,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SGM/2/V10.72/English/SGM_THINKDIAG_V10.72_EN.zip",
        "zyVersion": "V53.60",
        "isNewPath": 1,
        "versionDetailId": 2306,
        "softUpdateTime": 1641985308355,
        "softApplicableAreaId": 1,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 230,
        "softName": "Isuzu/Isuzu (Thailand)",
        "softPackageID": "JPISUZU",
        "erpCode": "X0220",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 18126997,
        "versionNo": "V10.48",
        "platType": 2,
        "androidSoftId": 71648,
        "iosSoftId": 62491,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/JPISUZU/2/V10.48/English/JPISUZU_THINKDIAG_V10.48_EN.zip",
        "zyVersion": "V18.10",
        "isNewPath": 1,
        "versionDetailId": 2608,
        "softUpdateTime": 1645411993612,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 228,
        "softName": "GM/Chevrolet/Cadillac/Buick",
        "softPackageID": "GM",
        "erpCode": "X0218",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 80961979,
        "versionNo": "V11.22",
        "platType": 2,
        "androidSoftId": 71666,
        "iosSoftId": 62476,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/GM/2/V11.22/English/GM_THINKDIAG_V11.22_EN.zip",
        "zyVersion": "V49.95",
        "isNewPath": 1,
        "versionDetailId": 2310,
        "softUpdateTime": 1654509748652,
        "softApplicableAreaId": 1,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 226,
        "softName": "EOBD/OBDII",
        "softPackageID": "EOBD2",
        "erpCode": "X0216",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 6907673,
        "versionNo": "V10.28",
        "platType": 2,
        "androidSoftId": 71472,
        "iosSoftId": 62525,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/EOBD2/2/V10.28/English/EOBD2_THINKDIAG_V10.28_EN.zip",
        "zyVersion": "V23.03",
        "isNewPath": 0,
        "versionDetailId": 1317,
        "softUpdateTime": 1662697588310,
        "softApplicableAreaId": 10,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 225,
        "softName": "Sprinter",
        "softPackageID": "SPRINTER",
        "erpCode": "X0215",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 61638616,
        "versionNo": "V10.46",
        "platType": 2,
        "androidSoftId": 71716,
        "iosSoftId": 62620,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SPRINTER/2/V10.46/English/SPRINTER_THINKDIAG_V10.46_EN.zip",
        "zyVersion": "V21.92",
        "isNewPath": 1,
        "versionDetailId": 2344,
        "softUpdateTime": 1654507962727,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 224,
        "softName": "Smart",
        "softPackageID": "SMART",
        "erpCode": "X0214",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 24931517,
        "versionNo": "V10.22",
        "platType": 2,
        "androidSoftId": 71638,
        "iosSoftId": 62524,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SMART/2/V10.22/English/SMART_THINKDIAG_V10.22_EN.zip",
        "zyVersion": "V18.45",
        "isNewPath": 1,
        "versionDetailId": 2385,
        "softUpdateTime": 1648693627926,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 216,
        "softName": "Brilliance",
        "softPackageID": "HUACHEN",
        "erpCode": "X0205",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 15722214,
        "versionNo": "V10.24",
        "platType": 2,
        "androidSoftId": 75206,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/HUACHEN/2/V10.24/English/HUACHEN_THINKDIAG_V10.24_EN.zip",
        "zyVersion": "V30.94",
        "isNewPath": 0,
        "versionDetailId": 2226,
        "softUpdateTime": 1652358167909,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 214,
        "softName": "BYD",
        "softPackageID": "FLYER",
        "erpCode": "X0203",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 38334762,
        "versionNo": "V10.24",
        "platType": 2,
        "androidSoftId": 75653,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/FLYER/2/V10.24/English/FLYER_THINKDIAG_V10.24_EN.zip",
        "zyVersion": "V19.70",
        "isNewPath": 1,
        "versionDetailId": 1509,
        "softUpdateTime": 1653370500681,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 210,
        "softName": "VOLKSWAGEN",
        "softPackageID": "VW",
        "erpCode": "X0199",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 85161132,
        "versionNo": "V10.40",
        "platType": 2,
        "androidSoftId": 71719,
        "iosSoftId": 62543,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/VW/2/V10.40/English/VW_THINKDIAG_V10.40_EN.zip",
        "zyVersion": "V29.10",
        "isNewPath": 0,
        "versionDetailId": 2305,
        "softUpdateTime": 1660642825245,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 209,
        "softName": "Citroen",
        "softPackageID": "CITROEN",
        "erpCode": "X0198",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 74128661,
        "versionNo": "V10.30",
        "platType": 2,
        "androidSoftId": 71735,
        "iosSoftId": 62566,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/CITROEN/2/V10.30/English/CITROEN_THINKDIAG_V10.30_EN.zip",
        "zyVersion": "V42.01",
        "isNewPath": 1,
        "versionDetailId": 1924,
        "softUpdateTime": 1654507465122,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 207,
        "softName": "Nissan (Zhengzhou)",
        "softPackageID": "ZZNISSAN",
        "erpCode": "X0196",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 11990778,
        "versionNo": "V10.28",
        "platType": 2,
        "androidSoftId": 81490,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/ZZNISSAN/2/V10.28/English/ZZNISSAN_THINKDIAG_V10.28_EN.zip",
        "zyVersion": "V12.11",
        "isNewPath": 1,
        "versionDetailId": 2076,
        "softUpdateTime": 1683207139632,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 206,
        "softName": "Zotye",
        "softPackageID": "ZHONGTAI",
        "erpCode": "X0195",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 8852348,
        "versionNo": "V10.06",
        "platType": 2,
        "androidSoftId": 75680,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/ZHONGTAI/2/V10.06/English/ZHONGTAI_THINKDIAG_V10.06_EN.zip",
        "zyVersion": "V18.20",
        "isNewPath": 1,
        "versionDetailId": 2242,
        "softUpdateTime": 1640778295637,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 199,
        "softName": "Subaru",
        "softPackageID": "SUBARU",
        "erpCode": "X0189",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 25184889,
        "versionNo": "V10.68",
        "platType": 2,
        "androidSoftId": 71708,
        "iosSoftId": 62547,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SUBARU/2/V10.68/English/SUBARU_THINKDIAG_V10.68_EN.zip",
        "zyVersion": "V26.41",
        "isNewPath": 1,
        "versionDetailId": 2238,
        "softUpdateTime": 1640777796851,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 198,
        "softName": "Ssangyong",
        "softPackageID": "SSANGYONG",
        "erpCode": "X0188",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 39844033,
        "versionNo": "V10.12",
        "platType": 2,
        "androidSoftId": 75674,
        "iosSoftId": 62596,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SSANGYONG/2/V10.12/English/SSANGYONG_THINKDIAG_V10.12_EN.zip",
        "zyVersion": "V19.70",
        "isNewPath": 1,
        "versionDetailId": 2615,
        "softUpdateTime": 1646136740449,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 197,
        "softName": "Skoda",
        "softPackageID": "SKODA",
        "erpCode": "X0187",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 67225047,
        "versionNo": "V10.18",
        "platType": 2,
        "androidSoftId": 71714,
        "iosSoftId": 62542,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SKODA/2/V10.18/English/SKODA_THINKDIAG_V10.18_EN.zip",
        "zyVersion": "V28.57",
        "isNewPath": 0,
        "versionDetailId": 2386,
        "softUpdateTime": 1660642839003,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 196,
        "softName": "Seat",
        "softPackageID": "SEAT",
        "erpCode": "X0186",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 68119878,
        "versionNo": "V10.20",
        "platType": 2,
        "androidSoftId": 71465,
        "iosSoftId": 62477,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SEAT/2/V10.20/English/SEAT_THINKDIAG_V10.20_EN.zip",
        "zyVersion": "V28.52",
        "isNewPath": 1,
        "versionDetailId": 2237,
        "softUpdateTime": 1640777640119,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 188,
        "softName": "Chery",
        "softPackageID": "QIRUI_TY",
        "erpCode": "X0176",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 17739137,
        "versionNo": "V10.22",
        "platType": 2,
        "androidSoftId": 75202,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/QIRUI_TY/2/V10.22/English/QIRUI_TY_THINKDIAG_V10.22_EN.zip",
        "zyVersion": "V57.83",
        "isNewPath": 1,
        "versionDetailId": 2383,
        "softUpdateTime": 1640770530424,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 179,
        "softName": "Mitsubishi",
        "softPackageID": "MITSUBISHI",
        "erpCode": "X0167",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 80662346,
        "versionNo": "V10.48",
        "platType": 2,
        "androidSoftId": 71470,
        "iosSoftId": 62647,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/MITSUBISHI/2/V10.48/English/MITSUBISHI_THINKDIAG_V10.48_EN.zip",
        "zyVersion": "V35.65",
        "isNewPath": 1,
        "versionDetailId": 2435,
        "softUpdateTime": 1654507998457,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 177,
        "softName": "Proton (Malaysia)",
        "softPackageID": "MALAYSIA PROTON",
        "erpCode": "X0165",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 11949618,
        "versionNo": "V10.12",
        "platType": 2,
        "androidSoftId": 95778,
        "iosSoftId": 62617,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/MALAYSIA PROTON/2/V10.12/English/MALAYSIA PROTON_THINKDIAG_V10.12_EN.zip",
        "zyVersion": "V15.11",
        "isNewPath": 1,
        "versionDetailId": 1786,
        "softUpdateTime": 1645514552548,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 176,
        "softName": "Perodua (Malaysia)",
        "softPackageID": "MALAYSIA PERODUA",
        "erpCode": "X0164",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 7073620,
        "versionNo": "V10.16",
        "platType": 2,
        "androidSoftId": 91433,
        "iosSoftId": 62516,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/MALAYSIA PERODUA/2/V10.16/English/MALAYSIA PERODUA_THINKDIAG_V10.16_EN.zip",
        "zyVersion": "V14.60",
        "isNewPath": 1,
        "versionDetailId": 1764,
        "softUpdateTime": 1645514562396,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 174,
        "softName": "Luxgen",
        "softPackageID": "LUXGEN",
        "erpCode": "X0162",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 4381413,
        "versionNo": "V10.00",
        "platType": 2,
        "androidSoftId": 75683,
        "iosSoftId": 62666,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/LUXGEN/2/V10.00/English/LUXGEN_THINKDIAG_V10.00_EN.zip",
        "zyVersion": "V10.72",
        "isNewPath": 1,
        "versionDetailId": 130,
        "softUpdateTime": 1640776669353,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 172,
        "softName": "Changan",
        "softPackageID": "CHANGAN",
        "erpCode": "X160",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 31397699,
        "versionNo": "V10.42",
        "platType": 2,
        "androidSoftId": 75668,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/CHANGAN/2/V10.42/English/CHANGAN_THINKDIAG_V10.42_EN.zip",
        "zyVersion": "V18.31",
        "isNewPath": 1,
        "versionDetailId": 2219,
        "softUpdateTime": 1654507402372,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 169,
        "softName": "Volvo",
        "softPackageID": "VOLVO",
        "erpCode": "X0157",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 15211696,
        "versionNo": "V10.54",
        "platType": 2,
        "androidSoftId": 71649,
        "iosSoftId": 62497,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/VOLVO/2/V10.54/English/VOLVO_THINKDIAG_V10.54_EN.zip",
        "zyVersion": "V45.00",
        "isNewPath": 1,
        "versionDetailId": 2616,
        "softUpdateTime": 1654165479980,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 168,
        "softName": "VAZ",
        "softPackageID": "VAZ",
        "erpCode": "X0156",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 7256592,
        "versionNo": "V10.08",
        "platType": 2,
        "androidSoftId": 92009,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/VAZ/2/V10.08/English/VAZ_THINKDIAG_V10.08_EN.zip",
        "zyVersion": "V16.13",
        "isNewPath": 1,
        "versionDetailId": 1301,
        "softUpdateTime": 1640777969841,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 162,
        "softName": "Qoros",
        "softPackageID": "QOROS",
        "erpCode": "X0151",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 1789164,
        "versionNo": "V10.00",
        "platType": 2,
        "androidSoftId": 81472,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/QOROS/2/V10.00/English/QOROS_THINKDIAG_V10.00_EN.zip",
        "zyVersion": "V10.11",
        "isNewPath": 1,
        "versionDetailId": 161,
        "softUpdateTime": 1640777054226,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 160,
        "softName": "LUFENG",
        "softPackageID": "LUFENG",
        "erpCode": "X0150",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 3120449,
        "versionNo": "V10.00",
        "platType": 2,
        "androidSoftId": 106224,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/LUFENG/2/V10.00/English/LUFENG_THINKDIAG_V10.00_EN.zip",
        "zyVersion": "V16.52",
        "isNewPath": 1,
        "versionDetailId": 159,
        "softUpdateTime": 1654149901883,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 159,
        "softName": "SGMW/United Pakistan",
        "softPackageID": "LIUWEI_TY",
        "erpCode": "X0149",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 15990711,
        "versionNo": "V10.26",
        "platType": 2,
        "androidSoftId": 75666,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/LIUWEI_TY/2/V10.26/English/LIUWEI_TY_THINKDIAG_V10.26_EN.zip",
        "zyVersion": "V21.41",
        "isNewPath": 1,
        "versionDetailId": 2070,
        "softUpdateTime": 1641984809659,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 157,
        "softName": "Lifan",
        "softPackageID": "LIFAN",
        "erpCode": "X0147",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 7197594,
        "versionNo": "V10.12",
        "platType": 2,
        "androidSoftId": 75696,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/LIFAN/2/V10.12/English/LIFAN_THINKDIAG_V10.12_EN.zip",
        "zyVersion": "V13.14",
        "isNewPath": 1,
        "versionDetailId": 2232,
        "softUpdateTime": 1640828017151,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 151,
        "softName": "Tata (India)",
        "softPackageID": "INDIANTATA",
        "erpCode": "X0141",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 8313754,
        "versionNo": "V10.20",
        "platType": 2,
        "androidSoftId": 91432,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/INDIANTATA/2/V10.20/English/INDIANTATA_THINKDIAG_V10.20_EN.zip",
        "zyVersion": "V15.41",
        "isNewPath": 1,
        "versionDetailId": 1700,
        "softUpdateTime": 1640775922548,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 150,
        "softName": "Maruti (India)",
        "softPackageID": "INDIANMARUTI",
        "erpCode": "X0140",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 24311400,
        "versionNo": "V10.14",
        "platType": 2,
        "androidSoftId": 91431,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/INDIANMARUTI/2/V10.14/English/INDIANMARUTI_THINKDIAG_V10.14_EN.zip",
        "zyVersion": "V17.40",
        "isNewPath": 1,
        "versionDetailId": 1693,
        "softUpdateTime": 1640775909034,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 148,
        "softName": "Honda/Acura",
        "softPackageID": "HONDA",
        "erpCode": "X0138",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 36655051,
        "versionNo": "V10.54",
        "platType": 2,
        "androidSoftId": 71868,
        "iosSoftId": 62621,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/HONDA/2/V10.54/English/HONDA_THINKDIAG_V10.54_EN.zip",
        "zyVersion": "V49.70",
        "isNewPath": 1,
        "versionDetailId": 2466,
        "softUpdateTime": 1641984563768,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 145,
        "softName": "Hafei",
        "softPackageID": "HAFEI",
        "erpCode": "X0135",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 2407485,
        "versionNo": "V10.00",
        "platType": 2,
        "androidSoftId": 75207,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/HAFEI/2/V10.00/English/HAFEI_THINKDIAG_V10.00_EN.zip",
        "zyVersion": "V25.08",
        "isNewPath": 0,
        "versionDetailId": 148,
        "softUpdateTime": 1645587526093,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 144,
        "softName": "Foton",
        "softPackageID": "FUTIAN",
        "erpCode": "X0134",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 9581822,
        "versionNo": "V10.20",
        "platType": 2,
        "androidSoftId": 75715,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/FUTIAN/2/V10.20/English/FUTIAN_THINKDIAG_V10.20_EN.zip",
        "zyVersion": "V14.10",
        "isNewPath": 0,
        "versionDetailId": 2374,
        "softUpdateTime": 1640778856645,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 133,
        "softName": "Audi",
        "softPackageID": "AUDI",
        "erpCode": "X0126",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 102680382,
        "versionNo": "V10.46",
        "platType": 2,
        "androidSoftId": 71706,
        "iosSoftId": 62592,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/AUDI/2/V10.46/English/AUDI_THINKDIAG_V10.46_EN.zip",
        "zyVersion": "V29.20",
        "isNewPath": 1,
        "versionDetailId": 2464,
        "softUpdateTime": 1640771203636,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 131,
        "softName": "Maserati",
        "softPackageID": "MASERATI",
        "erpCode": "X00124",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 24338999,
        "versionNo": "V10.42",
        "platType": 2,
        "androidSoftId": 75690,
        "iosSoftId": 74817,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/MASERATI/2/V10.42/English/MASERATI_THINKDIAG_V10.42_EN.zip",
        "zyVersion": "V12.15",
        "isNewPath": 1,
        "versionDetailId": 2369,
        "softUpdateTime": 1640776690865,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 130,
        "softName": "Porsche",
        "softPackageID": "PORSCHE",
        "erpCode": "X0123",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 137665976,
        "versionNo": "V10.46",
        "platType": 2,
        "androidSoftId": 71501,
        "iosSoftId": 62648,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/PORSCHE/2/V10.46/English/PORSCHE_THINKDIAG_V10.46_EN.zip",
        "zyVersion": "V24.52",
        "isNewPath": 1,
        "versionDetailId": 2233,
        "softUpdateTime": 1640776986982,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 129,
        "softName": "Toyota/Lexus",
        "softPackageID": "TOYOTA",
        "erpCode": "X0122",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 74008808,
        "versionNo": "V10.62",
        "platType": 2,
        "androidSoftId": 71474,
        "iosSoftId": 62470,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/TOYOTA/2/V10.62/English/TOYOTA_THINKDIAG_V10.62_EN.zip",
        "zyVersion": "V51.50",
        "isNewPath": 1,
        "versionDetailId": 2387,
        "softUpdateTime": 1654166017228,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 128,
        "softName": "KIA",
        "softPackageID": "KIA",
        "erpCode": "X0121",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 89050215,
        "versionNo": "V10.80",
        "platType": 2,
        "androidSoftId": 71761,
        "iosSoftId": 62523,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/KIA/2/V10.80/English/KIA_THINKDIAG_V10.80_EN.zip",
        "zyVersion": "V46.50",
        "isNewPath": 1,
        "versionDetailId": 2612,
        "softUpdateTime": 1653272879736,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 102,
        "softName": "ZX Auto",
        "softPackageID": "ZHONGXING",
        "erpCode": "X0095",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 10293923,
        "versionNo": "V10.28",
        "platType": 2,
        "androidSoftId": 75214,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/ZHONGXING/2/V10.28/English/ZHONGXING_THINKDIAG_V10.28_EN.zip",
        "zyVersion": "V21.70",
        "isNewPath": 1,
        "versionDetailId": 2243,
        "softUpdateTime": 1640828502068,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 77,
        "softName": "Maxus",
        "softPackageID": "MAXUS",
        "erpCode": "X0069",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 15379714,
        "versionNo": "V10.20",
        "platType": 2,
        "androidSoftId": 75724,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/MAXUS/2/V10.20/English/MAXUS_THINKDIAG_V10.20_EN.zip",
        "zyVersion": "V10.60",
        "isNewPath": 0,
        "versionDetailId": 2029,
        "softUpdateTime": 1642749646199,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 73,
        "softName": "KARRY_TY",
        "softPackageID": "KARRY_TY",
        "erpCode": "X0065",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 20302091,
        "versionNo": "V10.14",
        "platType": 2,
        "androidSoftId": 94417,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/KARRY_TY/2/V10.14/English/KARRY_TY_THINKDIAG_V10.14_EN.zip",
        "zyVersion": "V11.20",
        "isNewPath": 1,
        "versionDetailId": 2610,
        "softUpdateTime": 1654149925961,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 68,
        "softName": "Gonow",
        "softPackageID": "JIAO",
        "erpCode": "X0060",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 3299939,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 75599,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/JIAO/2/V10.02/English/JIAO_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V13.60",
        "isNewPath": 1,
        "versionDetailId": 503,
        "softUpdateTime": 1640776295697,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 65,
        "softName": "Ferrari",
        "softPackageID": "FERRARI",
        "erpCode": "X0058",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 8382830,
        "versionNo": "V10.20",
        "platType": 2,
        "androidSoftId": 75693,
        "iosSoftId": 76429,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/FERRARI/2/V10.20/English/FERRARI_THINKDIAG_V10.20_EN.zip",
        "zyVersion": "V11.50",
        "isNewPath": 1,
        "versionDetailId": 2496,
        "softUpdateTime": 1645411962233,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 63,
        "softName": "JAC/JAC Refine",
        "softPackageID": "JACTY",
        "erpCode": "X0056",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 26063172,
        "versionNo": "V10.32",
        "platType": 2,
        "androidSoftId": 75204,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/JACTY/2/V10.32/English/JACTY_THINKDIAG_V10.32_EN.zip",
        "zyVersion": "V19.54",
        "isNewPath": 1,
        "versionDetailId": 2117,
        "softUpdateTime": 1641984667877,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 56,
        "softName": "Hyundai",
        "softPackageID": "HYUNDAI",
        "erpCode": "X0049",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 1,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 101072020,
        "versionNo": "V10.70",
        "platType": 2,
        "androidSoftId": 71764,
        "iosSoftId": 62496,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/HYUNDAI/2/V10.70/English/HYUNDAI_THINKDIAG_V10.70_EN.zip",
        "zyVersion": "V52.50",
        "isNewPath": 1,
        "versionDetailId": 2628,
        "softUpdateTime": 1654507609699,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 55,
        "softName": "Haima",
        "softPackageID": "HMAZDA",
        "erpCode": "X0048",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 11961675,
        "versionNo": "V10.12",
        "platType": 2,
        "androidSoftId": 75706,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/HMAZDA/2/V10.12/English/HMAZDA_THINKDIAG_V10.12_EN.zip",
        "zyVersion": "V13.41",
        "isNewPath": 1,
        "versionDetailId": 1559,
        "softUpdateTime": 1640769854145,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 50,
        "softName": "Fiat/Abarth/Alfa Romeo/Lancia",
        "softPackageID": "FIAT",
        "erpCode": "X0043",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 23858065,
        "versionNo": "V11.12",
        "platType": 2,
        "androidSoftId": 71659,
        "iosSoftId": 62568,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/FIAT/2/V11.12/English/FIAT_THINKDIAG_V11.12_EN.zip",
        "zyVersion": "V38.80",
        "isNewPath": 1,
        "versionDetailId": 2497,
        "softUpdateTime": 1654507491747,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 43,
        "softName": "GWM",
        "softPackageID": "CHANGCHENG",
        "erpCode": "X0036",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 34786854,
        "versionNo": "V10.58",
        "platType": 2,
        "androidSoftId": 75208,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/CHANGCHENG/2/V10.58/English/CHANGCHENG_THINKDIAG_V10.58_EN.zip",
        "zyVersion": "V37.13",
        "isNewPath": 1,
        "versionDetailId": 2478,
        "softUpdateTime": 1654507582032,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 41,
        "softName": "Fiat (Brazil)",
        "softPackageID": "BXFIAT",
        "erpCode": "X0034",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 5909314,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 93670,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/BXFIAT/2/V10.02/English/BXFIAT_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V10.55",
        "isNewPath": 1,
        "versionDetailId": 1281,
        "softUpdateTime": 1640771575039,
        "softApplicableAreaId": 1,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 31,
        "softName": "Jinlong",
        "softPackageID": "JINLONG",
        "erpCode": "X0024",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 9626474,
        "versionNo": "V10.10",
        "platType": 2,
        "androidSoftId": 75215,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/JINLONG/2/V10.10/English/JINLONG_THINKDIAG_V10.10_EN.zip",
        "zyVersion": "V13.23",
        "isNewPath": 0,
        "versionDetailId": 2067,
        "softUpdateTime": 1640776345372,
        "softApplicableAreaId": 3,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 22,
        "softName": "Daewoo",
        "softPackageID": "DAEWOO",
        "erpCode": "X0015",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 2716811,
        "versionNo": "V10.02",
        "platType": 2,
        "androidSoftId": 75671,
        "iosSoftId": 62598,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/DAEWOO/2/V10.02/English/DAEWOO_THINKDIAG_V10.02_EN.zip",
        "zyVersion": "V27.20",
        "isNewPath": 1,
        "versionDetailId": 798,
        "softUpdateTime": 1640778425684,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 20,
        "softName": "GM (Brazil)",
        "softPackageID": "BXGM",
        "erpCode": "X0013",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 5653636,
        "versionNo": "V10.12",
        "platType": 2,
        "androidSoftId": 91429,
        "iosSoftId": null,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/BXGM/2/V10.12/English/BXGM_THINKDIAG_V10.12_EN.zip",
        "zyVersion": "V14.55",
        "isNewPath": 1,
        "versionDetailId": 2337,
        "softUpdateTime": 1640771588023,
        "softApplicableAreaId": 1,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 17,
        "softName": "AutoSearch",
        "softPackageID": "AUTOSEARCH",
        "erpCode": "X0010",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 92623695,
        "versionNo": "V10.22",
        "platType": 2,
        "androidSoftId": 72690,
        "iosSoftId": 62561,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/AUTOSEARCH/2/V10.22/English/AUTOSEARCH_THINKDIAG_V10.22_EN.zip",
        "zyVersion": "V11.15",
        "isNewPath": 1,
        "versionDetailId": 2428,
        "softUpdateTime": 1640771322147,
        "softApplicableAreaId": 10,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 16,
        "softName": "Saab",
        "softPackageID": "SAAB",
        "erpCode": "X0009",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 5033344,
        "versionNo": "V10.08",
        "platType": 2,
        "androidSoftId": 75629,
        "iosSoftId": 62474,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/SAAB/2/V10.08/English/SAAB_THINKDIAG_V10.08_EN.zip",
        "zyVersion": "V23.35",
        "isNewPath": 0,
        "versionDetailId": 2235,
        "softUpdateTime": 1661845812641,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 15,
        "softName": "Opel/Vauxhall/Opel (South Africa)",
        "softPackageID": "OPEL",
        "erpCode": "X0008",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 20342357,
        "versionNo": "V10.84",
        "platType": 2,
        "androidSoftId": 71728,
        "iosSoftId": 62567,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/OPEL/2/V10.84/English/OPEL_THINKDIAG_V10.84_EN.zip",
        "zyVersion": "V43.50",
        "isNewPath": 1,
        "versionDetailId": 2231,
        "softUpdateTime": 1641984993325,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 14,
        "softName": "Mazda",
        "softPackageID": "MAZDA",
        "erpCode": "X0007",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 32278956,
        "versionNo": "V10.46",
        "platType": 2,
        "androidSoftId": 71675,
        "iosSoftId": 62494,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/MAZDA/2/V10.46/English/MAZDA_THINKDIAG_V10.46_EN.zip",
        "zyVersion": "V44.10",
        "isNewPath": 1,
        "versionDetailId": 2302,
        "softUpdateTime": 1693895077007,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 13,
        "softName": "Daihatsu",
        "softPackageID": "DAIHATSU",
        "erpCode": "X0006",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 12048344,
        "versionNo": "V10.24",
        "platType": 2,
        "androidSoftId": 71737,
        "iosSoftId": 62495,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/DAIHATSU/2/V10.24/English/DAIHATSU_THINKDIAG_V10.24_EN.zip",
        "zyVersion": "V20.70",
        "isNewPath": 1,
        "versionDetailId": 2375,
        "softUpdateTime": 1640778411009,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 11,
        "softName": "Holden (Australia)",
        "softPackageID": "AUSTHOLDEN",
        "erpCode": "X0004",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 43326922,
        "versionNo": "V10.16",
        "platType": 2,
        "androidSoftId": 91427,
        "iosSoftId": 62518,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/AUSTHOLDEN/2/V10.16/English/AUSTHOLDEN_THINKDIAG_V10.16_EN.zip",
        "zyVersion": "V44.20",
        "isNewPath": 1,
        "versionDetailId": 2294,
        "softUpdateTime": 1640913355754,
        "softApplicableAreaId": 0,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      },
      {
        "id": 10,
        "softName": "Aston Martin",
        "softPackageID": "ASTONMARTIN",
        "erpCode": "X0003",
        "softType": 1,
        "serverCurrentTime": 1788788908313,
        "price": 0,
        "priceUnit": 1,
        "isHotModel": 0,
        "is_free": 1,
        "free_date": 0,
        "renew_diagnosis_sign": 0,
        "scan_plus_system": 0,
        "fileSize": 5637779,
        "versionNo": "V10.22",
        "platType": 2,
        "androidSoftId": 75722,
        "iosSoftId": 75219,
        "is_renew": null,
        "is_send": null,
        "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/ASTONMARTIN/2/V10.22/English/ASTONMARTIN_THINKDIAG_V10.22_EN.zip",
        "zyVersion": "V11.00",
        "isNewPath": 0,
        "versionDetailId": 2292,
        "softUpdateTime": 1656469660342,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
        "availableEndTime": null
      }
    ],
    "reset_select_number": 0,
    "model_select_number": 0,
    "softProductList": {
      "s": 0
    }
  
                 "softProductList": {
            "s": 0
        }
    }
});

// مسار جلب إعدادات التطبيق وتوجيه الروابط إلى سيرفرك الخاص //
app.get('/api/app_config', (req, res) => {
    const myServer = "https://hasan-mohammad.onrender.com";

    res.json({
        "code": 0,
        "message": "success",
        "data": {
            "VIP_URL": `${myServer}/vip_pay/home_new?identification=vipPage&filter_user_group=1`,
            "SOFTWARE_PAY_URL": `${myServer}/pay/cloudpay`,
            "GATEWAY_FCA_URL": `${myServer}/m/FCA_describe?channel=FCA_describe&good_id=174&identification=FCA_describe`,
            "GATEWAY_VAG_URL": `${myServer}/shopPage/gateway?channel=VAG&good_id=291&identification=VAG`,
            "GATEWAY_BENZ_URL": `${myServer}/shopPage/gateway?channel=BENZ_URL&good_id=290&identification=BENZ_URL`,
            "GATEWAY_RENAULT_URL": `${myServer}/shopPage/gateway?channel=renaultGateway&good_id=85&identification=renaultGateway`,
            "MY_COUPONS_LIST_URL": `${myServer}/community_app/myCoupons`,
            "AI_ANALYSE": `${myServer}/ai_h5/predictionAnalyse`,
            "AI_REPAIR": `${myServer}/ai_h5/aiRepairEstimate`,
            "AI_PLAN": `${myServer}/ai_h5/maintenancePlan`,
            "AI_FUNCTION_EQUITY": `${myServer}/ai_h5/aiFunctionEquity`
        },
        "time": Math.floor(Date.now() / 1000),
        "ip": req.ip || "127.0.0.1"
    });
});

app.listen(port, () => {
    console.log(`Server is running on port ${port}`);
});
              "downloadLink": "https://downloadapp.mythinkcar.com/app_soft/ASTONMARTIN/2/V10.22/English/ASTONMARTIN_THINKDIAG_V10.22_EN.zip",
        "zyVersion": "V11.00",
        "isNewPath": 0,
        "versionDetailId": 2292,
        "softUpdateTime": 1656469660342,
        "softApplicableAreaId": 2,
        "lanType": "English",
        "lanId": "1001",
            "availableEndTime": null
    }
],
"reset_select_number": 0,
"model_select_number": 0,
"softProductList": {
    "s": 0
}
});


// مسار جلب إعدادات التطبيق وتوجيه الروابط إلى سيرفرك الخاص //
app.get('/api/app_config', (req, res) => {
    const myServer = "https://hasan-mohammad.onrender.com";

    res.json({
        "code": 0,
        "message": "success",
        "data": {
            "VIP_URL": `${myServer}/vip_pay/home_new?identification=vipPage&filter_user_group=1`,
            "SOFTWARE_PAY_URL": `${myServer}/pay/cloudpay`,
            "GATEWAY_FCA_URL": `${myServer}/m/FCA_describe?channel=FCA_describe&good_id=174&identification=FCA_describe`,
            "GATEWAY_VAG_URL": `${myServer}/shopPage/gateway?channel=VAG&good_id=291&identification=VAG`,
            "GATEWAY_BENZ_URL": `${myServer}/shopPage/gateway?channel=BENZ_URL&good_id=290&identification=BENZ_URL`,
            "GATEWAY_RENAULT_URL": `${myServer}/shopPage/gateway?channel=renaultGateway&good_id=85&identification=renaultGateway`,
            "MY_COUPONS_LIST_URL": `${myServer}/community_app/myCoupons`,
            "AI_ANALYSE": `${myServer}/ai_h5/predictionAnalyse`,
            "AI_REPAIR": `${myServer}/ai_h5/aiRepairEstimate`,
            "AI_PLAN": `${myServer}/ai_h5/maintenancePlan`,
            "AI_FUNCTION_EQUITY": `${myServer}/ai_h5/aiFunctionEquity`
        },
        "time": Math.floor(Date.now() / 1000),
        "ip": req.ip || "127.0.0.1"
    });
});

app.listen(port, () => {
    console.log(`Server is running on port ${port}`);
});
       